### PR TITLE
Fix npm postinstall

### PR DESCRIPTION
**Pull request by jareware**
After building the project:

```
$ docker run --rm cgm-remote-monitor ls /opt/app/static
admin
api-docs.html
audio
browserconfig.xml
clock.html
css
glyphs
images
index.html
js
manifest.json
profile
report
robots.txt
```

Notice how `bower_components` is missing after the build. This (obviously) breaks the web UI. Running the `postinstall` task manually fixes this. I remember having this same issue with Docker & these older npm versions before.

### CODE REVIEW

**Comment by jareware** [comment]
Also, I see no reason to EXPOSE all those ports, just exposing the default 1337 seems enough.

**Comment by jasoncalabrese** [comment]
I don't think there's any reason we need to require these older node version, I'm going to add some travis tests for node 4.x and 5.x

**Comment by jasoncalabrese** [comment]
Looks like we'll need to update some dependencies for 4.x and 5.x, build fails for both https://github.com/nightscout/cgm-remote-monitor/pull/1389

**Comment by jareware** [comment]
Yeah, the 0.12 series is somewhat dated already, so this'd only be a temporary fix.

**Comment by jasoncalabrese** [comment]
I'm not using docker, so I'm going to assume this is working and merge it

**Pull request merged**
